[package]
name = "wgan"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.20.1", features = ["train", "autodiff", "dataset", "cuda"] }   
image = "0.25.9"
rand = "0.10.0"
wincode = { version = "0.4.1", features = ["derive"] }
